tracer/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/', include('app01.urls', namespace='app01')),
    url(r'^', include('web.urls')),

]

web/urls.py
from django.conf.urls import url, include

from web.views import account, home, project, statistics, wiki, file, setting, issues, dashboard

urlpatterns = [
    url(r'^register/$', account.register, name="register"),
    url(r'^login/sms/$', account.login_sms, name="login_sms"),
    url(r'^login/$', account.login, name="login"),
    url(r'^logout/$', account.logout, name="logout"),
    url(r'^send_sms/$', account.send_sms, name="send_sms"),
    url(r'^image_code/$', account.image_code, name="image_code"),
    url(r'^index/$', home.index, name="index"),
    url(r'^price/$', home.price, name="price"),
    url(r'^payment/(?P<package_id>\d+)/$', home.payment, name="payment"),
    url(r'^pay/$', home.pay, name='pay'),
    url(r'^pay/notify/$', home.pay_notify, name='pay_policy'),

    # url(r'^cos/credential/$', file.cos_credential, name='file'),
    url(r'^project/list/$', project.project_list, name="project_list"),

    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\w+)/$', project.project_star, name="project_star"),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\w+)/$', project.project_unstar, name="project_unstar"),

    url(r'^manage/(?P<project_id>\w+)/', include([

        url(r'^statistics/$', statistics.statistics, name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        url(r'^statistics/project/user/$', statistics.statistics_project_user, name='statistics_project_user'),

        url(r'^file/$', file.file, name='file'),
        url(r'^file/delete$', file.file_delete, name='file_delete'),
        url(r'^file/post', file.file_post, name='file_post'),
        url(r'^file/download/(?P<file_id>\d+)', file.file_download, name='file_download'),
        url(r'^cos/credential$', file.cos_credential, name='cos_credential'),

        url(r'^wiki/$', wiki.wiki, name='wiki'),
        url(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)$', wiki.wiki_edit, name='wiki_edit'),
        url(r'^wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),
        url(r'^wiki/del/(?P<wiki_id>\d+)$', wiki.wiki_del, name='wiki_del'),
        url(r'^wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),

        url(r'^setting/$', setting.setting, name='setting'),
        url(r'^setting/project_delete/$', setting.project_delete, name='project_delete'),

        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/edit/(?P<issues_id>\d+)$', issues.issues_edit, name='issues_edit'),
        url(r'^issues/record/(?P<issues_id>\d+)/$', issues.issues_record, name='issues_record'),
        url(r'^issues/change/(?P<issues_id>\d+)/$', issues.issues_change, name='issues_change'),
        url(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

        url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
        url(r'^dashboard/issues/chart$', dashboard.issues_chart, name='issues_chart'),

    ])),
    url(r'^invite/join/(?P<code>\w+)/$', issues.invite_join, name="invite_join"),
]

web/models.py
from django.db import models


class UserInfo(models.Model):
    """
    用户信息表
    """
    username = models.CharField(max_length=32, verbose_name='用户名', unique=True)
    email = models.EmailField(max_length=32, verbose_name='邮箱', unique=True)
    mobile_phone = models.CharField(max_length=32, verbose_name='手机号', unique=True)
    password = models.CharField(max_length=32, verbose_name='密码')
    project_num = models.SmallIntegerField(default=0, verbose_name='已创建项目数量')

    def __str__(self):
        return self.username

    def increase_projectnum(self):
        self.project_num += 1
        self.save(update_fields=['project_num'])


class OrderDetail(models.Model):
    """
    订单详情表
    """
    status_choices = (
        (1, '未支付'),
        (2, '已支付')
    )

    order_id = models.CharField(max_length=64, verbose_name='订单ID', unique=True)
    status = models.CharField(max_length=32, verbose_name='支付状态', choices=status_choices, default=2)
    user = models.ForeignKey('UserInfo', verbose_name='用户ID')
    price_policy = models.ForeignKey('PricePackage', verbose_name='购买套餐')
    num = models.IntegerField(verbose_name='购买数量', help_text='0表示无限期')
    origin_price = models.IntegerField(verbose_name='原价')
    actually_paid = models.IntegerField(verbose_name='实付价格')
    start_time = models.DateTimeField(null=True, blank=True)
    expire_time = models.DateTimeField(null=True, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)


class PricePackage(models.Model):
    """
    价格套餐信息表
    """
    type_choices = (
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他'),
    )

    type = models.CharField(max_length=32, choices=type_choices, verbose_name='套餐类型')
    title = models.CharField(max_length=32, verbose_name='标题')
    price = models.PositiveIntegerField(verbose_name='价格/年')
    project_limit = models.PositiveIntegerField(verbose_name='可创建项目数')
    member_limit = models.PositiveIntegerField(verbose_name='单个项目可参与人员数')
    space_limit = models.PositiveIntegerField(verbose_name='单个项目文件总大小', help_text='G')
    file_size_limit = models.PositiveIntegerField(verbose_name='单个文件大小', help_text='M')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')


class Project(models.Model):
    """
    项目信息表
    """
    COLOR_CHOICES = (
        (1, "#56b8eb"),  # 56b8eb
        (2, "#f28033"),  # f28033
        (3, "#ebc656"),  # ebc656
        (4, "#a2d148"),  # a2d148
        (5, "#20BFA4"),  # #20BFA4
        (6, "#7461c2"),  # 7461c2,
        (7, "#20bfa3"),  # 20bfa3,
    )

    title = models.CharField(max_length=32, verbose_name='项目名称')
    color = models.SmallIntegerField(choices=COLOR_CHOICES, verbose_name='颜色', default=1)
    star_target = models.BooleanField(default=False, verbose_name='星标')
    member_num = models.IntegerField(default=1, verbose_name='成员数量')
    creator = models.ForeignKey('UserInfo', verbose_name='创建者', related_name='user')
    used_space = models.IntegerField(default=0, verbose_name='项目已用空间/KB')
    info = models.TextField(verbose_name='项目描述')
    bucket = models.CharField(max_length=128, verbose_name='cos桶')
    region = models.CharField(max_length=32, verbose_name='cos区域')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.title


class ProjectUser(models.Model):
    """ 项目参与者 """
    user = models.ForeignKey(verbose_name='参与者', to='UserInfo')
    project = models.ForeignKey(verbose_name='项目', to='Project')
    star = models.BooleanField(verbose_name='星标', default=False)
    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)


class Wiki(models.Model):
    """wiki文档相关"""
    user = models.ForeignKey(verbose_name='创建者', to='UserInfo')
    project = models.ForeignKey(verbose_name='项目', to='Project')
    title = models.CharField(max_length=64, verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    parent = models.ForeignKey(verbose_name='父文档', to='Wiki', null=True, blank=True, related_name='children')
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True, null=True, blank=True)
    depth = models.IntegerField(verbose_name='深度', default=1)

    def __str__(self):
        return self.title


class File(models.Model):
    """文件相关"""

    type_choices = (
        (1, '文件'),
        (2, '文件夹'),
    )

    name = models.CharField(verbose_name='文件名', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project')
    type = models.CharField(verbose_name='文件类型', max_length=32, choices=type_choices, default=2)
    file_size = models.IntegerField(verbose_name='文件大小', null=True, blank=True)
    file_path = models.CharField(verbose_name='文件路径', null=True, blank=True, max_length=255)
    user = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='creator')
    update_user = models.ForeignKey(verbose_name='更新者', to='UserInfo')
    parent = models.ForeignKey(verbose_name='上级目录', to='File', null=True, blank=True, related_name='children')
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True, null=True, blank=True)
    key = models.CharField(verbose_name='key', max_length=128, null=True, blank=True)


class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType')
    module = models.ForeignKey(verbose_name='模块', to='Module', null=True, blank=True)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)
    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """ 模块（里程碑）"""
    project = models.ForeignKey(verbose_name='项目', to='Project')
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """

    PROJECT_INIT_LIST = ["任务", '功能', 'Bug']

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project')

    def __str__(self):
        return self.title


class IssuesReply(models.Model):
    """ 问题回复"""

    reply_type_choices = (
        (1, '修改记录'),
        (2, '回复')
    )
    reply_type = models.IntegerField(verbose_name='类型', choices=reply_type_choices)

    issues = models.ForeignKey(verbose_name='问题', to='Issues')
    content = models.TextField(verbose_name='描述')
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_reply')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True)


class ProjectInvite(models.Model):
    """ 项目邀请码 """
    project = models.ForeignKey(verbose_name='项目', to='Project')
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_invite')

web/forms/file.py
# coding:utf-8
# @Author:ella


from django import forms
from web.forms.bootstrapForm import BootstrapForm
from web import models
from django.core.validators import ValidationError
from utils.tencent.cos import check_file


class FolderModelForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = models.File
        fields = ['name']

    def __init__(self, request, parent_object, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.parent_object = parent_object

    def clean_name(self):
        name = self.cleaned_data['name']

        # 检测当前目录下有没有重名的文件夹
        quertset = models.File.objects.filter(name=name, project=self.request.current_user.project, type=2)

        if self.parent_object:
            exists = quertset.filter(parent=self.parent_object).exists()

        else:
            exists = quertset.filter(parent__isnull=True).exists()

        if exists:
            raise ValidationError('文件夹已存在')

        return name


class FileModelForm(BootstrapForm, forms.ModelForm):
    etag = forms.CharField(label='ETag')

    class Meta:
        model = models.File
        exclude = ['user', 'update_user', 'project', 'type', 'update_datetime', 'create_time']

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_file_path(self):
        file_path = self.cleaned_data['file_path']

        return f"https://{file_path}"


    """
    def clean(self):
        etag = self.cleaned_data['etag']
        key = self.cleaned_data['key']
        size = self.cleaned_data['file_size']

        if not key or not etag:
            return self.cleaned_data

        # 向COS校验文件是否合法
        from qcloud_cos.cos_exception import CosServiceError

        try:
            result = check_file(self.request.current_user.projrct.bucket, self.request.current_user.projrct.region, key)

        except CosServiceError as e:
            self.add_error('key', '文件不存在')
            return self.cleaned_data

        cos_etag = result.get('ETag')
        if cos_etag != etag:
            self.add_error('etag', 'ETag错误')

        if size != result.get('Content-Length'):
            self.add_error('size', '文件大小不一致')

        return self.cleaned_data
        
        """

web/views/dashboard.py
# coding:utf-8
# @Author:ella

import collections
from django.shortcuts import render, redirect, HttpResponse
from web import models
from django.db.models import Count
from django.http import JsonResponse
import datetime, time


def dashboard(request, project_id):
    status_dict = collections.OrderedDict()

    for key, text in models.Issues.status_choices:
        status_dict[key] = {'text': text, 'count': 0}

    status_object_list = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    for item in status_object_list:
        status_dict[item['status']]['count'] = item['ct']

    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id', 'user__username')

    top_ten_object = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by('-id')[0:10]
    # print(top_ten_object)

    context = {
        "status_dict": status_dict,
        "user_list": user_list,
        'top_ten_object': top_ten_object,
    }

    return render(request, 'dashboard.html', context)


def issues_chart(request, project_id):
    # 最近30天，每天创建的问题数量

    # print(123)

    today = datetime.datetime.now().date()

    data_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        data_dict[date.strftime('%Y-%m-%d')] = [time.mktime(date.timetuple()) * 1000, 0]

    # pymysql -->'ctime': "DATE_FORMAT(web_transaction.create_datetime,'%%Y-%%m-%%d')"
    result = models.Issues.objects.filter(project_id=project_id, create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={'ctime': "strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}).values('ctime').annotate(ct=Count('id'))

    for item in result:
        data_dict[item['ctime']][1] = item['ct']

    return JsonResponse({'status': True, 'data': list(data_dict.values())})

web/views/setting.py
# coding:utf-8
# @Author:ella

from django.shortcuts import render, redirect, HttpResponse
from utils.tencent.cos import delete_bucket
from web import models


def setting(request, project_id):
    return render(request, 'setting.html')


def project_delete(request, project_id):
    if request.method == 'GET':
        return render(request, 'project_delete.html')

    project_name = request.POST.get('project_name')

    if not project_name or project_name != request.current_user.project.title:
        return render(request, 'project_delete.html', {'error': '项目名填写错误'})

    if request.current_user.user != request.current_user.project.creator:
        return render(request, 'project_delete.html', {'error': '只有项目创建者可删除项目，请联系项目管理员'})

    # 删除桶 + 删除数据库数据
    delete_bucket(request.current_user.project.bucket, request.current_user.project.region)
    print(1)
    models.Project.objects.filter(id=request.current_user.project.id).delete()
    print(2)

    return redirect('project_list')

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 首页 {% endblock %}

{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static 'img/index/index-1.png' %}">
        <img src="{% static 'img/index/index-2.png' %}">
        <img src="{% static 'img/index/index-3.png' %}">
        <img src="{% static 'img/index/index-4.png' %}">
    </div>

{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}

{% block title %}用户短信登录{% endblock %}

{% load static %}
{% block css %}

    <link rel="stylesheet" href="{% static 'css/account.css' %}">

    <style>
        .error-msg {
            font-size: 13px;
            color: red;
            position: absolute;
        }

    </style>

{% endblock %}


{% block content %}

    <div class="account">
        <div class="title">用户短信登录</div>

        <form id="loginSmsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-xs-5">
                                <input id="smsBtn" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>

                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>

                {% endif %}
            {% endfor %}

        <div style="float:right; margin-top: 5px">

            <a href="{% url 'login' %}">用户名密码登录?</a>

        </div>

            <div class="row">
                <div class="col-xs-3">
                    <input id= 'btnSubmit' type="button" class="btn btn-primary" value="登  录"/>
                </div>
            </div>

        </form>
    </div>





{% endblock %}



{% block js %}

    <script>

        $(function () {

            bindClickBtnSms();
            bindClickBtnSubmit();

        });

        /* 点击发送验证码*/

        function bindClickBtnSms() {

            $('#smsBtn').click(function () {
                $('.error-msg').empty();

                var mobilePhone = $('#id_mobile_phone').val();


                $.ajax({
                    url:{% url 'send_sms' %},
                    type: "GET",
                    data: {
                        mobile_phone: mobilePhone,
                        tpl: 'login',

                    },
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res);

                        if (res.status) {
                            {#console.log('发送成功');#}
                            sendSmsRemind();

                        } else {
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);

                            })
                        }
                    }
                })
            })

        }

        /* 发送验证码倒计时 */
        function sendSmsRemind() {

            var $smsbtn = $('#smsBtn');

            $smsbtn.prop('disabled', true);
            var time = 60;

            var remind = setInterval(function () {

                $smsbtn.val(time + '秒后重新发送');

                time = time - 1;
                if (time < 1) {
                    $smsbtn.val('点击发送验证码').prop('disabled', false);
                }
            }, 1000)
        }

        /* 点击登录按钮*/
        function bindClickBtnSubmit() {

            $('#btnSubmit').click(function () {

                $('.error-msg').empty();

                $.ajax({
                    url: '{% url 'login_sms' %}',
                    type: 'POST',
                    data: $('#loginSmsForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {

                        if (res.status) {
                            location.href = res.data;
                        }
                        else {
                            $.each(res.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })

                        }
                    }
                })
            });


        }


    </script>


{% endblock %}

web/templates/project_list.html
{% extends 'layout/backbasic.html' %}


{% block title %}

    项目管理

{% endblock %}

{% block css %}

    <style>
        .error-msg {
            font-size: 13px;
            color: red;
            position: absolute;
        }

        .project {
            margin-top: 10px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>




{% endblock %}


{% block content %}

    <div class="container-fluid">

        <!-- Button trigger modal -->
        <button style="margin: 20px 0px;" id='newProject' type="button" class="btn btn-primary"
                data-toggle="modal" data-target="#myModal">
            <i class="fa fa-plus-circle" aria-hidden="true"></i>创建新项目
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">新建项目</h4>
                    </div>
                    <div class="modal-body">


                        <form id="newProjectForm" action="" method="post">
                            {% csrf_token %}

                            {% for field in form %}


                                    <div class="form-group">
                                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg">{{ field.errors.0 }}</span>
                                    </div>


                            {% endfor %}

                        </form>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <input type="button" id='btnCreate' class="btn btn-primary" value="创建">
                    </div>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-star" aria-hidden="true"></i>&nbsp;星标项目</h3>
            </div>
            <div class="panel-body">
                {% for item in project_sort.star %}

                    <div class="item">
                        <a href="{% url 'dashboard' item.value.id %}" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.title }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_unstar' project_type=item.type project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: gold"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.member_num }}</span>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bars" aria-hidden="true"></i>&nbsp;我创建的项目</h3>
            </div>
            <div class="panel-body">
                {% for item in project_sort.my %}

                    <div class="item">
                        <a href="{% url 'dashboard' item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.title }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='my' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.member_num }}</span>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-handshake-o" aria-hidden="true"></i>&nbsp;我参与的项目</h3>
            </div>
            <div class="panel-body">
                {% for item in project_sort.join %}

                    <div class="item">
                        <a href="{% url 'dashboard' item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.title }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='join' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.member_num }}</span>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>


    </div>
{% endblock %}

{% block js %}

    <script>


        $(function () {
            bindClickBtnCreate();
            hideRadio();

        });


        function bindClickBtnCreate() {

            $('#btnCreate').click(function () {

                    $('.error-msg').empty();

                    $.ajax({
                        url: '{% url 'project_list' %}',
                        type: 'POST',
                        data: $('#newProjectForm').serialize(),
                        dataType: 'JSON',
                        success: function (res) {

                            if (res.status) {
                                {#$('#myModal').modal('hide')#}
                                location.href = location.href;
                                {#location.reload();#}
                            } else {
                                $.each(res.error, function (key, value) {
                                    $('#id_' + key).next().text(value[0]);
                                })
                            }
                        }
                    })
                }
            )


        }


        function hideRadio() {
            $('.radio_bg').hide()
        }


    </script>

{% endblock %}