app01/urls.py
from django.conf.urls import url

from app01 import views

urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^send_sms/$', views.send_sms, name="send_sms"),
    url(r'^test/$', views.test, name="test"),
    url(r'^cos/credential/$', views.cos_credential, name='file'),
]

tracer/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/', include('app01.urls', namespace='app01')),
    url(r'^', include('web.urls')),

]

web/urls.py
from django.conf.urls import url, include

from web.views import account, home, project, statistics, wiki, file, setting, issues, dashboard

urlpatterns = [
    url(r'^register/$', account.register, name="register"),
    url(r'^login/sms/$', account.login_sms, name="login_sms"),
    url(r'^login/$', account.login, name="login"),
    url(r'^logout/$', account.logout, name="logout"),
    url(r'^send_sms/$', account.send_sms, name="send_sms"),
    url(r'^image_code/$', account.image_code, name="image_code"),
    url(r'^index/$', home.index, name="index"),
    url(r'^price/$', home.price, name="price"),
    url(r'^payment/(?P<package_id>\d+)/$', home.payment, name="payment"),
    url(r'^pay/$', home.pay, name='pay'),
    url(r'^pay/notify/$', home.pay_notify, name='pay_policy'),

    # url(r'^cos/credential/$', file.cos_credential, name='file'),
    url(r'^project/list/$', project.project_list, name="project_list"),

    url(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\w+)/$', project.project_star, name="project_star"),
    url(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\w+)/$', project.project_unstar, name="project_unstar"),

    url(r'^manage/(?P<project_id>\w+)/', include([

        url(r'^statistics/$', statistics.statistics, name='statistics'),
        url(r'^statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        url(r'^statistics/project/user/$', statistics.statistics_project_user, name='statistics_project_user'),

        url(r'^file/$', file.file, name='file'),
        url(r'^file/delete$', file.file_delete, name='file_delete'),
        url(r'^file/post', file.file_post, name='file_post'),
        url(r'^file/download/(?P<file_id>\d+)', file.file_download, name='file_download'),
        url(r'^cos/credential$', file.cos_credential, name='cos_credential'),

        url(r'^wiki/$', wiki.wiki, name='wiki'),
        url(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        url(r'^wiki/edit/(?P<wiki_id>\d+)$', wiki.wiki_edit, name='wiki_edit'),
        url(r'^wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),
        url(r'^wiki/del/(?P<wiki_id>\d+)$', wiki.wiki_del, name='wiki_del'),
        url(r'^wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),

        url(r'^setting/$', setting.setting, name='setting'),
        url(r'^setting/project_delete/$', setting.project_delete, name='project_delete'),

        url(r'^issues/$', issues.issues, name='issues'),
        url(r'^issues/edit/(?P<issues_id>\d+)$', issues.issues_edit, name='issues_edit'),
        url(r'^issues/record/(?P<issues_id>\d+)/$', issues.issues_record, name='issues_record'),
        url(r'^issues/change/(?P<issues_id>\d+)/$', issues.issues_change, name='issues_change'),
        url(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

        url(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
        url(r'^dashboard/issues/chart$', dashboard.issues_chart, name='issues_chart'),

    ])),
    url(r'^invite/join/(?P<code>\w+)/$', issues.invite_join, name="invite_join"),
]

app01/models.py
from django.db import models


class UserInfo(models.Model):
    username = models.CharField(max_length=32, verbose_name='用户名')
    email = models.EmailField(max_length=32, verbose_name='邮箱')
    mobile_phone = models.CharField(max_length=32, verbose_name='手机号')
    password = models.CharField(max_length=32, verbose_name='密码')

app01/forms.py
import re
import hashlib

from django import forms

from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

import redis

from app01 import models
from django.conf import settings


class RegForm(forms.ModelForm):
    phone = forms.CharField(
        label="手机号",
        widget=forms.TextInput,
        validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', "无效的手机号")])

    password = forms.CharField(label="密码", widget=forms.PasswordInput)

    confirm_password = forms.CharField(label="确认密码", widget=forms.PasswordInput)

    code = forms.CharField(label="验证码")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["placeholder"] = "请输入{}".format(field.label)

    def clean_username(self):
        username = self.cleaned_data.get("username")

        pattern = r'[a-zA-Z0-9_-]{4,16}$'

        if not re.match(pattern, username):
            raise ValidationError("用户名4到16位（字母，数字，下划线，减号）")

        return username

    def clean_password(self):
        password = self.cleaned_data.get("password")

        # pattern = '^.*(?=.{6,})(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*? ]).*$'

        # if not re.match(pattern, password):
        #     raise ValidationError("密码最少6位，包括至少1个大写字母，1个小写字母，1个数字，1个特殊字符")

        return password

    def clean(self):

        # check verification code
        code = self.cleaned_data.get("code", "")
        phone = self.cleaned_data.get("phone")

        conn = redis.Redis(host='127.0.0.1', port=6379, password="wuaihua123")

        if not code.encode() == conn.get(phone):
            self.add_error("code", "验证码错误")
            raise ValidationError("验证码错误")

        # check password and confirm_password
        password = self.cleaned_data.get("password", "")
        confirm_password = self.cleaned_data.get("confirm_password")

        if not password == confirm_password:
            self.add_error("confirm_password", "两次输入的密码不一致")

            raise ValidationError("两次输入的密码不一致")

        m = hashlib.md5()
        m.update(password.encode())

        encrypted_password = m.hexdigest()

        self.cleaned_data["password"] = encrypted_password

        return self.cleaned_data

    class Meta:

        model = models.UserInfo

        fields = [
            "username",
            "email",
            "password",
            "confirm_password",
            "phone",
            "code",
        ]

app01/views.py
import random
import re

from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.conf import settings
from utils.tencent.sms import send_sms_single

import redis

from app01 import forms


# Create your views here.

def send_sms(request):
    template_name = request.POST.get("tpl")

    template_id = settings.TENCENT_SMS_TEMPLATES.get(template_name)

    if not template_id:
        return HttpResponse("模板不存在")

    phone = request.POST.get("phone")

    pattern = r'^(1[3|4|5|6|7|8|9])\d{9}$'

    if not re.match(pattern, phone):
        return HttpResponse("无效的手机号码")

    code = random.randrange(1000, 9999)

    res = send_sms_single(phone, template_id, [code])

    if phone:
        conn = redis.Redis(host='127.0.0.1', port=6379, password="wuaihua123")

        conn.set(phone, code, ex=180)

        return HttpResponse("验证码成功发送")

    return HttpResponse(res["errmsg"])


def register(request):
    form_obj = forms.RegForm()

    if request.method == "POST":

        print(request.POST)
        form_obj = forms.RegForm(request.POST)

        if form_obj.is_valid():
            form_obj.save()

            return HttpResponse("注册成功")

    context = {
        "form_obj": form_obj,
    }

    return render(request, "app01/register.html", context)


# def test(request):
# phone = request.POST.get('phone')
# template_name = request.POST.get('tpl')
# template_id = settings.TENCENT_SMS_TEMPLATES.get(template_name)
#
# code = random.randrange(1000, 9999)
#
# res = [phone, template_id, [code]]
# print(res)
#
# if phone:
#     # conn = redis.Redis(**settings.REDIS_ARGS)
#     conn = redis.Redis(host='127.0.0.1', port=6379, password="wuaihua123")
#
#     conn.set(phone, code, ex=60)
#
#     return HttpResponse(f"验证码成功发送{code}")
#     # for testing without sending sms
#     # return HttpResponse(f"验证码: {code}")
#
# return JsonResponse({"status": True, "code": code})


def test(request):
    return render(request, 'app01/test.html')


def cos_credential(request):
    from sts.sts import Sts
    config = {
        # 临时密钥有效时长，单位是秒（30分钟=1800秒）
        'duration_seconds': 1800,
        # 固定密钥 id
        'secret_id': settings.TENCENT_COS_SECRET_ID,
        # 固定密钥 key
        'secret_key': settings.TENCENT_COS_SECRET_KEY,
        # 换成你的 bucket
        'bucket': "thefirst-18201048114-1585046638-1301482361",
        # 换成 bucket 所在地区
        'region': "ap-chengdu",
        # 这里改成允许的路径前缀，可以根据自己网站的用户登录态判断允许上传的具体路径
        # 例子： a.jpg 或者 a/* 或者 * (使用通配符*存在重大安全风险, 请谨慎评估使用)
        'allow_prefix': '*',
        # 密钥的权限列表。简单上传和分片需要以下的权限，其他权限列表请看 https://cloud.tencent.com/document/product/436/31923
        'allow_actions': [
            'name/cos:PostObject',
            # 'name/cos:DeleteObject',
            # "name/cos:UploadPart",
            # "name/cos:UploadPartCopy",
            # "name/cos:CompleteMultipartUpload",
            # "name/cos:AbortMultipartUpload",
            "*",
        ],

    }

    sts = Sts(config)
    result_dict = sts.get_credential()
    return JsonResponse(result_dict)

app01/templates/app01/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


</head>
<body>



    <div class="col-md-4 col-md-offset-4">

        <h1>注册</h1>

        <form action="" method="post">

            {% csrf_token %}

            {% for field in form_obj %}

                <div class="form-group {% if field.errors %}has-error{% endif %}">

                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>

                    {% if field.name == 'code' %}
                        <div class="clearfix">
                            <div class="col-md-8" style="padding-left:0;">
                                {{ field }}
                            </div>

                            <div class="col-md-4">
                                <button class="btn btn-default" id="send-code" type="button" >发送验证码</button>
                            </div>

                        </div>

                    {% else %}
                        {{ field }}
                    {% endif %}
                    <label class="control-label" for="{{ field.id_for_label }}">{{ field.errors.0 }}</label>

                </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary">注册</button>
        </form>

    </div>


    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script>
        $("#send-code").click(function(){

            let phone = $("#id_phone").val();

            let tpl = "register";

            let csrfmiddlewaretoken = $("[name='csrfmiddlewaretoken']").val();



            $.ajax({
                url:"{% url 'send_sms' %}",
                type: "POST",

                data:{
                    "tpl": tpl,
                    "phone": phone,
                    "csrfmiddlewaretoken": csrfmiddlewaretoken,
                },

                success: function(data){

                    alert(data);

                }

            {#$.ajax({#}
            {#    url:"{% url 'test' %}",#}
            {#    type: "POST",#}
            {##}
            {#    data:{#}
            {#        "tpl": tpl,#}
            {#        "phone": phone,#}
            {#        "csrfmiddlewaretoken": csrfmiddlewaretoken,#}
            {#    },#}
            {##}
            {#    success: function(code){#}
            {##}
            {#        alert(code);#}
            {##}
            {#    }#}
            });

        });

    </script>

</body>
</html>

app01/templates/app01/test.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
        <style>

        .panel-default .panel-heading {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }

    </style>
</head>
<body>


        <div class="container-fluid">


            <div class="panel panel-default">

                <div class="panel-heading">
                    <div>
                        <i class="fa fa-folder" aria-hidden="true"></i> 文件库
                    </div>
                    <div class="function">

                        <a type="button" class="btn btn-success btn-xs"
                           href="">
                            <i class="fa fa-upload" aria-hidden="true"></i> 上传文件
                        </a>

                        <a type="button" class="btn btn-primary btn-xs"
                           href="">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i> 新建文件夹
                        </a>

                    </div>
                </div>

                <div class="panel-body">
{#                    <h1>示例1：直接通过秘钥进行删除上传文件</h1>#}
                    <h1>示例2：临时凭证上传文件</h1>
                    <input type="file" name="upload_file" id="uploadFile" multiple/>

                </div>
            </div>
        </div>


    <script src="{% static 'js/jquery.min.js' %} "></script>

    <script src="{% static 'js/cos-js-sdk-v5.min.js' %} "></script>

    <script>
        var cos;

        $(function () {
            initCOS();
            bindChangeFileInput();
        });

        function initCOS() {
            cos = new COS({
                getAuthorization: function (options, callback) {
                    // 想django后台发送请求，获取临时凭证
                    $.get('/app01/cos/credential/', {
                        // 可从 options 取需要的参数
                    }, function (data) {
                        var credentials = data && data.credentials;
                        if (!data || !credentials) return console.error('credentials invalid');
                        callback({
                            TmpSecretId: credentials.tmpSecretId,
                            TmpSecretKey: credentials.tmpSecretKey,
                            XCosSecurityToken: credentials.sessionToken,
                            StartTime: data.startTime,
                            ExpiredTime: data.expiredTime,
                        });
                    });
                }
            });
        }

        function bindChangeFileInput() {
            $("#uploadFile").change(function () {
                // 获取要上传的所有文件对象列表
                var files = $(this)[0].files;
                $.each(files, function (index, fileObject) {
                    var fileName = fileObject.name;
                    // 上传文件
                    cos.putObject({
                        Bucket: 'thefirst-18201048114-1585046638-1301482361', /* 必须 */
                        Region: 'ap-chengdu',     /* 存储桶所在地域，必须字段 */
                        Key: fileName,              /* 必须 */
                        StorageClass: 'STANDARD',
                        Body: fileObject, // 上传文件对象
                        onProgress: function (progressData) {
                            console.log("文件上传进度--->", fileName, JSON.stringify(progressData));
                        }
                    }, function (err, data) {
                        console.log(err || data);
                    });

                })

            })
        }
    </script>


</body>
</html>